/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/ListUploadSessions_200_response_allOf_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ListUploadSessions_200_response_allOf_data::ListUploadSessions_200_response_allOf_data()
{
    m_SessionsIsSet = false;
}

ListUploadSessions_200_response_allOf_data::~ListUploadSessions_200_response_allOf_data()
{
}

void ListUploadSessions_200_response_allOf_data::validate()
{
    // TODO: implement validation
}

web::json::value ListUploadSessions_200_response_allOf_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SessionsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("sessions"))] = ModelBase::toJson(m_Sessions);
    }

    return val;
}

bool ListUploadSessions_200_response_allOf_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sessions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sessions")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<UploadSessionStatus>> refVal_setSessions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSessions);
            setSessions(refVal_setSessions);
            
        }
    }
    return ok;
}

void ListUploadSessions_200_response_allOf_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SessionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sessions")), m_Sessions));
    }
}

bool ListUploadSessions_200_response_allOf_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sessions"))))
    {
        std::vector<std::shared_ptr<UploadSessionStatus>> refVal_setSessions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sessions"))), refVal_setSessions );
        setSessions(refVal_setSessions);
    }
    return ok;
}


std::vector<std::shared_ptr<UploadSessionStatus>> ListUploadSessions_200_response_allOf_data::getSessions() const
{
    return m_Sessions;
}


void ListUploadSessions_200_response_allOf_data::setSessions(const std::vector<std::shared_ptr<UploadSessionStatus>>& value)
{
    m_Sessions = value;
    m_SessionsIsSet = true;
}

bool ListUploadSessions_200_response_allOf_data::sessionsIsSet() const
{
    return m_SessionsIsSet;
}

void ListUploadSessions_200_response_allOf_data::unsetSessions()
{
    m_SessionsIsSet = false;
}

}
}
}
}


