/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/SyncPlaylists_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SyncPlaylists_request::SyncPlaylists_request()
{
    m_Last_sync_seq = 0.0;
    m_Last_sync_seqIsSet = false;
    m_Client_op_id = utility::conversions::to_string_t("");
    m_Client_op_idIsSet = false;
}

SyncPlaylists_request::~SyncPlaylists_request()
{
}

void SyncPlaylists_request::validate()
{
    // TODO: implement validation
}

web::json::value SyncPlaylists_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Last_sync_seqIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_sync_seq"))] = ModelBase::toJson(m_Last_sync_seq);
    }
    if(m_Client_op_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("client_op_id"))] = ModelBase::toJson(m_Client_op_id);
    }

    return val;
}

bool SyncPlaylists_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_sync_seq"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_sync_seq")));
        if(!fieldValue.is_null())
        {
            double refVal_setLastSyncSeq;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastSyncSeq);
            setLastSyncSeq(refVal_setLastSyncSeq);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("client_op_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientOpId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientOpId);
            setClientOpId(refVal_setClientOpId);
            
        }
    }
    return ok;
}

void SyncPlaylists_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Last_sync_seqIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_sync_seq")), m_Last_sync_seq));
    }
    if(m_Client_op_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("client_op_id")), m_Client_op_id));
    }
}

bool SyncPlaylists_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_sync_seq"))))
    {
        double refVal_setLastSyncSeq;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_sync_seq"))), refVal_setLastSyncSeq );
        setLastSyncSeq(refVal_setLastSyncSeq);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))))
    {
        utility::string_t refVal_setClientOpId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))), refVal_setClientOpId );
        setClientOpId(refVal_setClientOpId);
    }
    return ok;
}


double SyncPlaylists_request::getLastSyncSeq() const
{
    return m_Last_sync_seq;
}

void SyncPlaylists_request::setLastSyncSeq(double value)
{
    m_Last_sync_seq = value;
    m_Last_sync_seqIsSet = true;
}

bool SyncPlaylists_request::lastSyncSeqIsSet() const
{
    return m_Last_sync_seqIsSet;
}

void SyncPlaylists_request::unsetLast_sync_seq()
{
    m_Last_sync_seqIsSet = false;
}
utility::string_t SyncPlaylists_request::getClientOpId() const
{
    return m_Client_op_id;
}


void SyncPlaylists_request::setClientOpId(const utility::string_t& value)
{
    m_Client_op_id = value;
    m_Client_op_idIsSet = true;
}

bool SyncPlaylists_request::clientOpIdIsSet() const
{
    return m_Client_op_idIsSet;
}

void SyncPlaylists_request::unsetClient_op_id()
{
    m_Client_op_idIsSet = false;
}

}
}
}
}


