/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * YouTubeApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_YouTubeApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_YouTubeApi_H_



#include "TombContracts/ApiClient.h"

#include "TombContracts/model/DownloadYouTube_200_response.h"
#include "TombContracts/model/DownloadYouTube_request.h"
#include "TombContracts/model/GetYouTubeDownloadStatus_200_response.h"
#include "TombContracts/model/SearchYouTube_200_response.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class TOMB_API YouTubeApi 
{
public:

    explicit YouTubeApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~YouTubeApi();

    /// <summary>
    /// Download audio from YouTube URL
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="downloadYouTubeRequest"></param>
    pplx::task<std::shared_ptr<DownloadYouTube_200_response>> downloadYouTube(
        std::shared_ptr<DownloadYouTube_request> downloadYouTubeRequest
    ) const;
    /// <summary>
    /// Get YouTube download task status
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="taskId"></param>
    pplx::task<std::shared_ptr<GetYouTubeDownloadStatus_200_response>> getYouTubeDownloadStatus(
        utility::string_t taskId
    ) const;
    /// <summary>
    /// Search YouTube videos
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="q">Search query</param>
    /// <param name="maxResults">Maximum number of results (optional, default to 0)</param>
    pplx::task<std::shared_ptr<SearchYouTube_200_response>> searchYouTube(
        utility::string_t q,
        boost::optional<int32_t> maxResults
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_YouTubeApi_H_ */

