/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DownloadYouTube_200_response_allOf_data.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DownloadYouTube_200_response_allOf_data_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DownloadYouTube_200_response_allOf_data_H_


#include "TombContracts/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class TOMB_API DownloadYouTube_200_response_allOf_data
    : public ModelBase
{
public:
    DownloadYouTube_200_response_allOf_data();
    virtual ~DownloadYouTube_200_response_allOf_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DownloadYouTube_200_response_allOf_data members


    utility::string_t getTaskId() const;
    bool taskIdIsSet() const;
    void unsetTask_id();
    void setTaskId(const utility::string_t& value);

    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);


protected:
    utility::string_t m_Task_id;
    bool m_Task_idIsSet;

    utility::string_t m_Status;
    bool m_StatusIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DownloadYouTube_200_response_allOf_data_H_ */
