/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AssociateNFC_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AssociateNFC_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AssociateNFC_request_H_


#include "TombContracts/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class TOMB_API AssociateNFC_request
    : public ModelBase
{
public:
    AssociateNFC_request();
    virtual ~AssociateNFC_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// AssociateNFC_request members


    utility::string_t getPlaylistId() const;
    bool playlistIdIsSet() const;
    void unsetPlaylist_id();
    void setPlaylistId(const utility::string_t& value);

    utility::string_t getTagId() const;
    bool tagIdIsSet() const;
    void unsetTag_id();
    void setTagId(const utility::string_t& value);

    utility::string_t getClientOpId() const;
    bool clientOpIdIsSet() const;
    void unsetClient_op_id();
    void setClientOpId(const utility::string_t& value);


protected:
    utility::string_t m_Playlist_id;
    bool m_Playlist_idIsSet;

    utility::string_t m_Tag_id;
    bool m_Tag_idIsSet;

    utility::string_t m_Client_op_id;
    bool m_Client_op_idIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AssociateNFC_request_H_ */
