/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetSystemLogs_200_response_allOf_data.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GetSystemLogs_200_response_allOf_data_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GetSystemLogs_200_response_allOf_data_H_


#include "TombContracts/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class TOMB_API GetSystemLogs_200_response_allOf_data
    : public ModelBase
{
public:
    GetSystemLogs_200_response_allOf_data();
    virtual ~GetSystemLogs_200_response_allOf_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetSystemLogs_200_response_allOf_data members


    std::vector<utility::string_t> getLogs() const;
    bool logsIsSet() const;
    void unsetLogs();
    void setLogs(const std::vector<utility::string_t>& value);


protected:
    std::vector<utility::string_t> m_Logs;
    bool m_LogsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GetSystemLogs_200_response_allOf_data_H_ */
