/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UploadSession.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UploadSession_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UploadSession_H_


#include "TombContracts/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class TOMB_API UploadSession
    : public ModelBase
{
public:
    UploadSession();
    virtual ~UploadSession();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UploadSession members


    utility::string_t getSessionId() const;
    bool sessionIdIsSet() const;
    void unsetSession_id();
    void setSessionId(const utility::string_t& value);

    utility::string_t getPlaylistId() const;
    bool playlistIdIsSet() const;
    void unsetPlaylist_id();
    void setPlaylistId(const utility::string_t& value);

    utility::string_t getFilename() const;
    bool filenameIsSet() const;
    void unsetFilename();
    void setFilename(const utility::string_t& value);

    /// <summary>
    /// Total file size in bytes
    /// </summary>
    int32_t getFileSize() const;
    bool fileSizeIsSet() const;
    void unsetFile_size();
    void setFileSize(int32_t value);

    /// <summary>
    /// Size of each chunk in bytes
    /// </summary>
    int32_t getChunkSize() const;
    bool chunkSizeIsSet() const;
    void unsetChunk_size();
    void setChunkSize(int32_t value);

    /// <summary>
    /// Total number of chunks
    /// </summary>
    int32_t getTotalChunks() const;
    bool totalChunksIsSet() const;
    void unsetTotal_chunks();
    void setTotalChunks(int32_t value);

    /// <summary>
    /// Optional file hash for verification
    /// </summary>
    utility::string_t getFileHash() const;
    bool fileHashIsSet() const;
    void unsetFile_hash();
    void setFileHash(const utility::string_t& value);

    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreated_at();
    void setCreatedAt(const utility::datetime& value);


protected:
    utility::string_t m_Session_id;
    bool m_Session_idIsSet;

    utility::string_t m_Playlist_id;
    bool m_Playlist_idIsSet;

    utility::string_t m_Filename;
    bool m_FilenameIsSet;

    int32_t m_File_size;
    bool m_File_sizeIsSet;

    int32_t m_Chunk_size;
    bool m_Chunk_sizeIsSet;

    int32_t m_Total_chunks;
    bool m_Total_chunksIsSet;

    utility::string_t m_File_hash;
    bool m_File_hashIsSet;

    utility::datetime m_Created_at;
    bool m_Created_atIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UploadSession_H_ */
