/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/CreatePlaylist_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CreatePlaylist_request::CreatePlaylist_request()
{
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Client_op_id = utility::conversions::to_string_t("");
    m_Client_op_idIsSet = false;
}

CreatePlaylist_request::~CreatePlaylist_request()
{
}

void CreatePlaylist_request::validate()
{
    // TODO: implement validation
}

web::json::value CreatePlaylist_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TitleIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_DescriptionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_Client_op_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("client_op_id"))] = ModelBase::toJson(m_Client_op_id);
    }

    return val;
}

bool CreatePlaylist_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("client_op_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientOpId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientOpId);
            setClientOpId(refVal_setClientOpId);
            
        }
    }
    return ok;
}

void CreatePlaylist_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_Client_op_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("client_op_id")), m_Client_op_id));
    }
}

bool CreatePlaylist_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))))
    {
        utility::string_t refVal_setClientOpId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))), refVal_setClientOpId );
        setClientOpId(refVal_setClientOpId);
    }
    return ok;
}


utility::string_t CreatePlaylist_request::getTitle() const
{
    return m_Title;
}


void CreatePlaylist_request::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool CreatePlaylist_request::titleIsSet() const
{
    return m_TitleIsSet;
}

void CreatePlaylist_request::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t CreatePlaylist_request::getDescription() const
{
    return m_Description;
}


void CreatePlaylist_request::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool CreatePlaylist_request::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void CreatePlaylist_request::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t CreatePlaylist_request::getClientOpId() const
{
    return m_Client_op_id;
}


void CreatePlaylist_request::setClientOpId(const utility::string_t& value)
{
    m_Client_op_id = value;
    m_Client_op_idIsSet = true;
}

bool CreatePlaylist_request::clientOpIdIsSet() const
{
    return m_Client_op_idIsSet;
}

void CreatePlaylist_request::unsetClient_op_id()
{
    m_Client_op_idIsSet = false;
}

}
}
}
}


