/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/GetSystemLogs_200_response_allOf_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

GetSystemLogs_200_response_allOf_data::GetSystemLogs_200_response_allOf_data()
{
    m_LogsIsSet = false;
}

GetSystemLogs_200_response_allOf_data::~GetSystemLogs_200_response_allOf_data()
{
}

void GetSystemLogs_200_response_allOf_data::validate()
{
    // TODO: implement validation
}

web::json::value GetSystemLogs_200_response_allOf_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_LogsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("logs"))] = ModelBase::toJson(m_Logs);
    }

    return val;
}

bool GetSystemLogs_200_response_allOf_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("logs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("logs")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setLogs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogs);
            setLogs(refVal_setLogs);
            
        }
    }
    return ok;
}

void GetSystemLogs_200_response_allOf_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_LogsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("logs")), m_Logs));
    }
}

bool GetSystemLogs_200_response_allOf_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("logs"))))
    {
        std::vector<utility::string_t> refVal_setLogs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("logs"))), refVal_setLogs );
        setLogs(refVal_setLogs);
    }
    return ok;
}


std::vector<utility::string_t> GetSystemLogs_200_response_allOf_data::getLogs() const
{
    return m_Logs;
}


void GetSystemLogs_200_response_allOf_data::setLogs(const std::vector<utility::string_t>& value)
{
    m_Logs = value;
    m_LogsIsSet = true;
}

bool GetSystemLogs_200_response_allOf_data::logsIsSet() const
{
    return m_LogsIsSet;
}

void GetSystemLogs_200_response_allOf_data::unsetLogs()
{
    m_LogsIsSet = false;
}

}
}
}
}


