/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/RestartSystem_200_response_allOf_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RestartSystem_200_response_allOf_data::RestartSystem_200_response_allOf_data()
{
    m_Restarting = false;
    m_RestartingIsSet = false;
}

RestartSystem_200_response_allOf_data::~RestartSystem_200_response_allOf_data()
{
}

void RestartSystem_200_response_allOf_data::validate()
{
    // TODO: implement validation
}

web::json::value RestartSystem_200_response_allOf_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_RestartingIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("restarting"))] = ModelBase::toJson(m_Restarting);
    }

    return val;
}

bool RestartSystem_200_response_allOf_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("restarting"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("restarting")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRestarting;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRestarting);
            setRestarting(refVal_setRestarting);
            
        }
    }
    return ok;
}

void RestartSystem_200_response_allOf_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_RestartingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("restarting")), m_Restarting));
    }
}

bool RestartSystem_200_response_allOf_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("restarting"))))
    {
        bool refVal_setRestarting;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("restarting"))), refVal_setRestarting );
        setRestarting(refVal_setRestarting);
    }
    return ok;
}


bool RestartSystem_200_response_allOf_data::isRestarting() const
{
    return m_Restarting;
}

void RestartSystem_200_response_allOf_data::setRestarting(bool value)
{
    m_Restarting = value;
    m_RestartingIsSet = true;
}

bool RestartSystem_200_response_allOf_data::restartingIsSet() const
{
    return m_RestartingIsSet;
}

void RestartSystem_200_response_allOf_data::unsetRestarting()
{
    m_RestartingIsSet = false;
}

}
}
}
}


