/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/SetVolume_200_response_allOf_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SetVolume_200_response_allOf_data::SetVolume_200_response_allOf_data()
{
    m_Volume = 0;
    m_VolumeIsSet = false;
}

SetVolume_200_response_allOf_data::~SetVolume_200_response_allOf_data()
{
}

void SetVolume_200_response_allOf_data::validate()
{
    // TODO: implement validation
}

web::json::value SetVolume_200_response_allOf_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_VolumeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("volume"))] = ModelBase::toJson(m_Volume);
    }

    return val;
}

bool SetVolume_200_response_allOf_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("volume"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("volume")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setVolume;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVolume);
            setVolume(refVal_setVolume);
            
        }
    }
    return ok;
}

void SetVolume_200_response_allOf_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_VolumeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("volume")), m_Volume));
    }
}

bool SetVolume_200_response_allOf_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("volume"))))
    {
        int32_t refVal_setVolume;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("volume"))), refVal_setVolume );
        setVolume(refVal_setVolume);
    }
    return ok;
}


int32_t SetVolume_200_response_allOf_data::getVolume() const
{
    return m_Volume;
}

void SetVolume_200_response_allOf_data::setVolume(int32_t value)
{
    m_Volume = value;
    m_VolumeIsSet = true;
}

bool SetVolume_200_response_allOf_data::volumeIsSet() const
{
    return m_VolumeIsSet;
}

void SetVolume_200_response_allOf_data::unsetVolume()
{
    m_VolumeIsSet = false;
}

}
}
}
}


