/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/ReorderPlaylist_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ReorderPlaylist_request::ReorderPlaylist_request()
{
    m_Track_idsIsSet = false;
    m_Client_op_id = utility::conversions::to_string_t("");
    m_Client_op_idIsSet = false;
}

ReorderPlaylist_request::~ReorderPlaylist_request()
{
}

void ReorderPlaylist_request::validate()
{
    // TODO: implement validation
}

web::json::value ReorderPlaylist_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Track_idsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("track_ids"))] = ModelBase::toJson(m_Track_ids);
    }
    if(m_Client_op_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("client_op_id"))] = ModelBase::toJson(m_Client_op_id);
    }

    return val;
}

bool ReorderPlaylist_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("track_ids"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("track_ids")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setTrackIds;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTrackIds);
            setTrackIds(refVal_setTrackIds);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("client_op_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientOpId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientOpId);
            setClientOpId(refVal_setClientOpId);
            
        }
    }
    return ok;
}

void ReorderPlaylist_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Track_idsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("track_ids")), m_Track_ids));
    }
    if(m_Client_op_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("client_op_id")), m_Client_op_id));
    }
}

bool ReorderPlaylist_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("track_ids"))))
    {
        std::vector<utility::string_t> refVal_setTrackIds;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("track_ids"))), refVal_setTrackIds );
        setTrackIds(refVal_setTrackIds);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))))
    {
        utility::string_t refVal_setClientOpId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("client_op_id"))), refVal_setClientOpId );
        setClientOpId(refVal_setClientOpId);
    }
    return ok;
}


std::vector<utility::string_t> ReorderPlaylist_request::getTrackIds() const
{
    return m_Track_ids;
}


void ReorderPlaylist_request::setTrackIds(const std::vector<utility::string_t>& value)
{
    m_Track_ids = value;
    m_Track_idsIsSet = true;
}

bool ReorderPlaylist_request::trackIdsIsSet() const
{
    return m_Track_idsIsSet;
}

void ReorderPlaylist_request::unsetTrack_ids()
{
    m_Track_idsIsSet = false;
}
utility::string_t ReorderPlaylist_request::getClientOpId() const
{
    return m_Client_op_id;
}


void ReorderPlaylist_request::setClientOpId(const utility::string_t& value)
{
    m_Client_op_id = value;
    m_Client_op_idIsSet = true;
}

bool ReorderPlaylist_request::clientOpIdIsSet() const
{
    return m_Client_op_idIsSet;
}

void ReorderPlaylist_request::unsetClient_op_id()
{
    m_Client_op_idIsSet = false;
}

}
}
}
}


