/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/ScanNFC_200_response_allOf_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ScanNFC_200_response_allOf_data::ScanNFC_200_response_allOf_data()
{
    m_Scanning = false;
    m_ScanningIsSet = false;
    m_Session_id = utility::conversions::to_string_t("");
    m_Session_idIsSet = false;
}

ScanNFC_200_response_allOf_data::~ScanNFC_200_response_allOf_data()
{
}

void ScanNFC_200_response_allOf_data::validate()
{
    // TODO: implement validation
}

web::json::value ScanNFC_200_response_allOf_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ScanningIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("scanning"))] = ModelBase::toJson(m_Scanning);
    }
    if(m_Session_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("session_id"))] = ModelBase::toJson(m_Session_id);
    }

    return val;
}

bool ScanNFC_200_response_allOf_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("scanning"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("scanning")));
        if(!fieldValue.is_null())
        {
            bool refVal_setScanning;
            ok &= ModelBase::fromJson(fieldValue, refVal_setScanning);
            setScanning(refVal_setScanning);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("session_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("session_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSessionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSessionId);
            setSessionId(refVal_setSessionId);
            
        }
    }
    return ok;
}

void ScanNFC_200_response_allOf_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ScanningIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("scanning")), m_Scanning));
    }
    if(m_Session_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("session_id")), m_Session_id));
    }
}

bool ScanNFC_200_response_allOf_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("scanning"))))
    {
        bool refVal_setScanning;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("scanning"))), refVal_setScanning );
        setScanning(refVal_setScanning);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("session_id"))))
    {
        utility::string_t refVal_setSessionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("session_id"))), refVal_setSessionId );
        setSessionId(refVal_setSessionId);
    }
    return ok;
}


bool ScanNFC_200_response_allOf_data::isScanning() const
{
    return m_Scanning;
}

void ScanNFC_200_response_allOf_data::setScanning(bool value)
{
    m_Scanning = value;
    m_ScanningIsSet = true;
}

bool ScanNFC_200_response_allOf_data::scanningIsSet() const
{
    return m_ScanningIsSet;
}

void ScanNFC_200_response_allOf_data::unsetScanning()
{
    m_ScanningIsSet = false;
}
utility::string_t ScanNFC_200_response_allOf_data::getSessionId() const
{
    return m_Session_id;
}


void ScanNFC_200_response_allOf_data::setSessionId(const utility::string_t& value)
{
    m_Session_id = value;
    m_Session_idIsSet = true;
}

bool ScanNFC_200_response_allOf_data::sessionIdIsSet() const
{
    return m_Session_idIsSet;
}

void ScanNFC_200_response_allOf_data::unsetSession_id()
{
    m_Session_idIsSet = false;
}

}
}
}
}


