/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RemoveTracksFromPlaylist_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RemoveTracksFromPlaylist_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RemoveTracksFromPlaylist_request_H_


#include "TombContracts/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class TOMB_API RemoveTracksFromPlaylist_request
    : public ModelBase
{
public:
    RemoveTracksFromPlaylist_request();
    virtual ~RemoveTracksFromPlaylist_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RemoveTracksFromPlaylist_request members


    /// <summary>
    /// List of track IDs to remove
    /// </summary>
    std::vector<utility::string_t> getTrackIds() const;
    bool trackIdsIsSet() const;
    void unsetTrack_ids();
    void setTrackIds(const std::vector<utility::string_t>& value);

    utility::string_t getClientOpId() const;
    bool clientOpIdIsSet() const;
    void unsetClient_op_id();
    void setClientOpId(const utility::string_t& value);


protected:
    std::vector<utility::string_t> m_Track_ids;
    bool m_Track_idsIsSet;

    utility::string_t m_Client_op_id;
    bool m_Client_op_idIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RemoveTracksFromPlaylist_request_H_ */
