/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PlaylistsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_PlaylistsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_PlaylistsApi_H_



#include "TombContracts/ApiClient.h"

#include "TombContracts/model/CreatePlaylist_201_response.h"
#include "TombContracts/model/CreatePlaylist_request.h"
#include "TombContracts/model/ListPlaylists_200_response.h"
#include "TombContracts/model/PlayerPlay_request.h"
#include "TombContracts/model/StartPlaylist_200_response.h"
#include "TombContracts/model/UpdatePlaylist_200_response.h"
#include "TombContracts/model/UpdatePlaylist_request.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class TOMB_API PlaylistsApi 
{
public:

    explicit PlaylistsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~PlaylistsApi();

    /// <summary>
    /// Create new playlist
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="createPlaylistRequest"></param>
    pplx::task<std::shared_ptr<CreatePlaylist_201_response>> createPlaylist(
        std::shared_ptr<CreatePlaylist_request> createPlaylistRequest
    ) const;
    /// <summary>
    /// Delete playlist
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="playlistId"></param>
    /// <param name="playerPlayRequest"> (optional)</param>
    pplx::task<void> deletePlaylist(
        utility::string_t playlistId,
        boost::optional<std::shared_ptr<PlayerPlay_request>> playerPlayRequest
    ) const;
    /// <summary>
    /// Get specific playlist
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="playlistId"></param>
    pplx::task<std::shared_ptr<CreatePlaylist_201_response>> getPlaylist(
        utility::string_t playlistId
    ) const;
    /// <summary>
    /// List all playlists with pagination
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="limit"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<ListPlaylists_200_response>> listPlaylists(
        boost::optional<int32_t> page,
        boost::optional<int32_t> limit
    ) const;
    /// <summary>
    /// Start playlist playback
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="playlistId"></param>
    /// <param name="playerPlayRequest"> (optional)</param>
    pplx::task<std::shared_ptr<StartPlaylist_200_response>> startPlaylist(
        utility::string_t playlistId,
        boost::optional<std::shared_ptr<PlayerPlay_request>> playerPlayRequest
    ) const;
    /// <summary>
    /// Update playlist
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="playlistId"></param>
    /// <param name="updatePlaylistRequest"> (optional)</param>
    pplx::task<std::shared_ptr<UpdatePlaylist_200_response>> updatePlaylist(
        utility::string_t playlistId,
        boost::optional<std::shared_ptr<UpdatePlaylist_request>> updatePlaylistRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_PlaylistsApi_H_ */

