/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.3.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetSystemInfo_200_response_allOf_data.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GetSystemInfo_200_response_allOf_data_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GetSystemInfo_200_response_allOf_data_H_


#include "TombContracts/ModelBase.h"

#include "TombContracts/model/SystemInfo.h"
#include <cpprest/details/basic_types.h>
#include "TombContracts/model/BackendCapabilities.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class SystemInfo;
class BackendCapabilities;


class TOMB_API GetSystemInfo_200_response_allOf_data
    : public ModelBase
{
public:
    GetSystemInfo_200_response_allOf_data();
    virtual ~GetSystemInfo_200_response_allOf_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetSystemInfo_200_response_allOf_data members


    std::shared_ptr<SystemInfo> getSystemInfo() const;
    bool systemInfoIsSet() const;
    void unsetSystem_info();
    void setSystemInfo(const std::shared_ptr<SystemInfo>& value);

    /// <summary>
    /// Firmware/application version
    /// </summary>
    utility::string_t getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();
    void setVersion(const utility::string_t& value);

    /// <summary>
    /// Device hostname
    /// </summary>
    utility::string_t getHostname() const;
    bool hostnameIsSet() const;
    void unsetHostname();
    void setHostname(const utility::string_t& value);

    /// <summary>
    /// System uptime in seconds
    /// </summary>
    double getUptime() const;
    bool uptimeIsSet() const;
    void unsetUptime();
    void setUptime(double value);

    std::shared_ptr<BackendCapabilities> getCapabilities() const;
    bool capabilitiesIsSet() const;
    void unsetCapabilities();
    void setCapabilities(const std::shared_ptr<BackendCapabilities>& value);


protected:
    std::shared_ptr<SystemInfo> m_System_info;
    bool m_System_infoIsSet;

    utility::string_t m_Version;
    bool m_VersionIsSet;

    utility::string_t m_Hostname;
    bool m_HostnameIsSet;

    double m_Uptime;
    bool m_UptimeIsSet;

    std::shared_ptr<BackendCapabilities> m_Capabilities;
    bool m_CapabilitiesIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GetSystemInfo_200_response_allOf_data_H_ */
