/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MoveTrack_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MoveTrack_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MoveTrack_request_H_


#include "TombContracts/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class TOMB_API MoveTrack_request
    : public ModelBase
{
public:
    MoveTrack_request();
    virtual ~MoveTrack_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MoveTrack_request members


    utility::string_t getSourcePlaylistId() const;
    bool sourcePlaylistIdIsSet() const;
    void unsetSource_playlist_id();
    void setSourcePlaylistId(const utility::string_t& value);

    utility::string_t getTargetPlaylistId() const;
    bool targetPlaylistIdIsSet() const;
    void unsetTarget_playlist_id();
    void setTargetPlaylistId(const utility::string_t& value);

    utility::string_t getTrackId() const;
    bool trackIdIsSet() const;
    void unsetTrack_id();
    void setTrackId(const utility::string_t& value);

    int32_t getTargetPosition() const;
    bool targetPositionIsSet() const;
    void unsetTarget_position();
    void setTargetPosition(int32_t value);

    utility::string_t getClientOpId() const;
    bool clientOpIdIsSet() const;
    void unsetClient_op_id();
    void setClientOpId(const utility::string_t& value);


protected:
    utility::string_t m_Source_playlist_id;
    bool m_Source_playlist_idIsSet;

    utility::string_t m_Target_playlist_id;
    bool m_Target_playlist_idIsSet;

    utility::string_t m_Track_id;
    bool m_Track_idIsSet;

    int32_t m_Target_position;
    bool m_Target_positionIsSet;

    utility::string_t m_Client_op_id;
    bool m_Client_op_idIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MoveTrack_request_H_ */
