/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchYouTube_200_response_allOf_data.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SearchYouTube_200_response_allOf_data_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SearchYouTube_200_response_allOf_data_H_


#include "TombContracts/ModelBase.h"

#include "TombContracts/model/YouTubeSearchResult.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class YouTubeSearchResult;


class TOMB_API SearchYouTube_200_response_allOf_data
    : public ModelBase
{
public:
    SearchYouTube_200_response_allOf_data();
    virtual ~SearchYouTube_200_response_allOf_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SearchYouTube_200_response_allOf_data members


    std::vector<std::shared_ptr<YouTubeSearchResult>> getResults() const;
    bool resultsIsSet() const;
    void unsetResults();
    void setResults(const std::vector<std::shared_ptr<YouTubeSearchResult>>& value);


protected:
    std::vector<std::shared_ptr<YouTubeSearchResult>> m_Results;
    bool m_ResultsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SearchYouTube_200_response_allOf_data_H_ */
