/**
 * TheOpenMusicBox API
 * Complete API contract definitions for TheOpenMusicBox - A Raspberry Pi-based music player system.  All API responses follow the UnifiedResponseService format with standardized envelopes. This specification is the source of truth for all client implementations (Web, Flutter, C++). 
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TombContracts/model/DownloadYouTube_200_response_allOf_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

DownloadYouTube_200_response_allOf_data::DownloadYouTube_200_response_allOf_data()
{
    m_Task_id = utility::conversions::to_string_t("");
    m_Task_idIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
}

DownloadYouTube_200_response_allOf_data::~DownloadYouTube_200_response_allOf_data()
{
}

void DownloadYouTube_200_response_allOf_data::validate()
{
    // TODO: implement validation
}

web::json::value DownloadYouTube_200_response_allOf_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Task_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("task_id"))] = ModelBase::toJson(m_Task_id);
    }
    if(m_StatusIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool DownloadYouTube_200_response_allOf_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("task_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("task_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTaskId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTaskId);
            setTaskId(refVal_setTaskId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    return ok;
}

void DownloadYouTube_200_response_allOf_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Task_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("task_id")), m_Task_id));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
}

bool DownloadYouTube_200_response_allOf_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("task_id"))))
    {
        utility::string_t refVal_setTaskId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("task_id"))), refVal_setTaskId );
        setTaskId(refVal_setTaskId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}


utility::string_t DownloadYouTube_200_response_allOf_data::getTaskId() const
{
    return m_Task_id;
}


void DownloadYouTube_200_response_allOf_data::setTaskId(const utility::string_t& value)
{
    m_Task_id = value;
    m_Task_idIsSet = true;
}

bool DownloadYouTube_200_response_allOf_data::taskIdIsSet() const
{
    return m_Task_idIsSet;
}

void DownloadYouTube_200_response_allOf_data::unsetTask_id()
{
    m_Task_idIsSet = false;
}
utility::string_t DownloadYouTube_200_response_allOf_data::getStatus() const
{
    return m_Status;
}


void DownloadYouTube_200_response_allOf_data::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool DownloadYouTube_200_response_allOf_data::statusIsSet() const
{
    return m_StatusIsSet;
}

void DownloadYouTube_200_response_allOf_data::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}
}
}


